-- 001_schema_and_indexes.sql
-- Core schema: all tables with proper Postgres types and constraints

create table bank_accounts (
  id            bigint generated by default as identity primary key,
  name          text not null unique,
  account_type  text not null default 'Bank',
  notes         text not null default '',
  active        boolean not null default true,
  sort_order    integer not null default 99,
  created_at    timestamptz not null default now()
);

create table account_openings (
  id               bigint generated by default as identity primary key,
  month            text not null,
  account          text not null references bank_accounts(name) on update cascade,
  opening_balance  numeric not null default 0,
  unique (month, account)
);

create table debt_creditors (
  id          bigint generated by default as identity primary key,
  name        text not null unique,
  sort_order  integer not null default 99,
  active      boolean not null default true
);

create table debt_entries (
  id               bigint generated by default as identity primary key,
  month            text not null,
  creditor_id      bigint not null references debt_creditors(id) on delete restrict,
  amount           numeric not null default 0,
  amount_paid      numeric not null default 0,
  status           text not null default 'unpaid' check (status in ('unpaid','partial','paid')),
  paid_at          timestamptz,
  amount_remaining numeric generated always as (amount - amount_paid) stored,
  unique (month, creditor_id)
);

create table income_entries (
  id              bigint generated by default as identity primary key,
  date            date not null,
  description     text not null default '',
  category        text not null default 'Other',
  account         text not null default 'Kotak' references bank_accounts(name) on update cascade,
  payment_method  text not null default 'UPI',
  amount          numeric not null default 0,
  month           text not null,
  notes           text not null default '',
  is_recurring    boolean not null default false,
  deleted         boolean not null default false
);

create table expenses (
  id              bigint generated by default as identity primary key,
  date            date not null,
  description     text not null default '',
  category        text not null default 'Other',
  account         text not null default 'Kotak' references bank_accounts(name) on update cascade,
  payment_method  text not null default 'UPI',
  amount          numeric not null default 0,
  month           text not null,
  notes           text not null default '',
  is_recurring    boolean not null default false,
  is_split        boolean not null default false,
  deleted         boolean not null default false
);

create table expense_splits (
  id           bigint generated by default as identity primary key,
  expense_id   bigint not null references expenses(id) on delete cascade,
  category     text not null,
  amount       numeric not null default 0,
  description  text not null default ''
);

create table budgets (
  id             bigint generated by default as identity primary key,
  category       text not null unique,
  monthly_limit  numeric not null default 0
);

create table transfers (
  id              bigint generated by default as identity primary key,
  date            date not null,
  from_account    text not null references bank_accounts(name) on update cascade,
  to_account      text not null references bank_accounts(name) on update cascade,
  amount          numeric not null default 0,
  payment_method  text not null default 'IMPS',
  description     text not null default '',
  notes           text not null default '',
  month           text not null,
  deleted         boolean not null default false,
  check (from_account <> to_account)
);

create table subscriptions (
  id             bigint generated by default as identity primary key,
  name           text not null,
  amount         numeric not null default 0,
  description    text not null default '',
  status         text not null default 'active',
  billing_day    integer not null default 1,
  billing_cycle  text not null default 'monthly' check (billing_cycle in ('monthly','annual')),
  deleted        boolean not null default false
);

create table subscription_payments (
  id               bigint generated by default as identity primary key,
  subscription_id  bigint not null references subscriptions(id) on delete cascade,
  cycle_month      text not null,
  status           text not null default 'due' check (status in ('due','paid','overdue')),
  amount           numeric not null default 0,
  due_date         date not null,
  paid_date        date,
  unique (subscription_id, cycle_month)
);

create table _changelog (
  id          bigint generated by default as identity primary key,
  ts          timestamptz not null default now(),
  table_name  text,
  row_id      bigint,
  action      text,
  details     jsonb
);

-- Indexes
create index idx_exp_month    on expenses(month);
create index idx_exp_del      on expenses(deleted);
create index idx_inc_month    on income_entries(month);
create index idx_inc_del      on income_entries(deleted);
create index idx_tr_month     on transfers(month);
create index idx_tr_del       on transfers(deleted);
create index idx_de_month     on debt_entries(month);
create index idx_de_creditor  on debt_entries(creditor_id);
create index idx_splits_eid   on expense_splits(expense_id);
create index idx_subpay_sub   on subscription_payments(subscription_id);
create index idx_subpay_cycle on subscription_payments(cycle_month);
